### ISSUE TITLE
Rate several packages . 

### ISSUE THREAD

**Issue by GocaninTs** [scottbedard/shipping#1]
Hello , i implemented your code into my project . 
Does your code solution for counting rates for several packages with different dimensions ? 
Thanks.

**Comment by scottbedard** [comment]
Sorry, this package was written many years ago and I no longer use or maintain it. I don't believe it supports getting multiple rates at once, so if you need this behavior you'll have to fork the project and implement it yourself.

Best of luck,
Scott
